### ISSUE TITLE
The README specifies a schema endpoint but swagger doesn't

### ISSUE THREAD

**Issue by MaxProfit** [permitio/cedar-agent#36]
The README specifies a schema endpoint but swagger doesn't

<img width="1559" alt="Screenshot 2024-09-28 at 11 13 02 PM" src="https://github.com/user-attachments/assets/bddb25c9-026c-4f1a-af46-0cff35860ae8">

**Comment by omer9564** [comment]
Hey @MaxProfit , you actually found a different issue.
We forgot to tag version `0.2.0` as `latest` on dockerhub and this feature was only released in `0.2.0`.
I updated the `latest` tag now to match `0.2.0`.
We are also working on an automated releasing process that will prevent these kind of issues from ever happening.

Thanks 🙏
